### ISSUE TITLE
Unable to find post_compile

### ISSUE THREAD

**Issue by durden** [mostafa-anm/sphinx-heroku-buildpack#5]
I see errors related to not finding the post_compile script.  I've even tried forking and moving post_compile to the bin folder.  Am I missing something in my setup?

remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Sphinx app detected
remote: cp: cannot create regular file ‘/tmp/build_bc558ca00f1bf4e2085a8882e1bcd3df/bin/post_compile’: No such file or directory
remote:  !     Push rejected, failed to compile Sphinx app.
remote:
remote:  !     Push failed

**Comment by amureki** [comment]
@durden can you provide a bit more information about this?
Is it still notional?
Are you using multiple buildpacks in your stack?

**Comment by codingjoe** [comment]
@durden thanks for report this bug. I fixed it and added proper tests to it won't break in the future.

Cheers!
-Johannes

**Comment by durden** [comment]
Thanks so much everyone. Also thanks in advance for a docker setup example!
